"""add api config fields to preferences

Revision ID: 3ad06cbfbd4c
Revises: dd309f94683e
Create Date: 2026-04-25 18:35:05.359674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad06cbfbd4c'
down_revision: Union[str, Sequence[str], None] = 'dd309f94683e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('api_provider', sa.String(length=50), nullable=False, server_default='openrouter'))
    op.add_column('preferences', sa.Column('openrouter_api_key', sa.String(length=255), nullable=True))
    op.add_column('preferences', sa.Column('apify_api_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'apify_api_token')
    op.drop_column('preferences', 'openrouter_api_key')
    op.drop_column('preferences', 'api_provider')
    # ### end Alembic commands ###
