"""add fast_model and smart_model to preferences

Revision ID: 4070433b0e60
Revises: 5a704cddeda2
Create Date: 2026-04-25 19:22:57.168509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4070433b0e60'
down_revision: Union[str, Sequence[str], None] = '5a704cddeda2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('fast_model', sa.String(length=150), nullable=True))
    op.add_column('preferences', sa.Column('smart_model', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'smart_model')
    op.drop_column('preferences', 'fast_model')
    # ### end Alembic commands ###
