"""add discovery runs and logs tables

Revision ID: 5a704cddeda2
Revises: 3ad06cbfbd4c
Create Date: 2026-04-25 19:16:58.483646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a704cddeda2'
down_revision: Union[str, Sequence[str], None] = '3ad06cbfbd4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('preference_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('managers_found', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_run_city_started', 'discovery_runs', ['city', 'started_at'], unique=False)
    op.create_index(op.f('ix_discovery_runs_city'), 'discovery_runs', ['city'], unique=False)
    op.create_index(op.f('ix_discovery_runs_started_at'), 'discovery_runs', ['started_at'], unique=False)
    op.create_table('discovery_run_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['discovery_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_run_seq', 'discovery_run_logs', ['run_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_discovery_run_logs_run_id'), 'discovery_run_logs', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovery_run_logs_run_id'), table_name='discovery_run_logs')
    op.drop_index('idx_log_run_seq', table_name='discovery_run_logs')
    op.drop_table('discovery_run_logs')
    op.drop_index(op.f('ix_discovery_runs_started_at'), table_name='discovery_runs')
    op.drop_index(op.f('ix_discovery_runs_city'), table_name='discovery_runs')
    op.drop_index('idx_run_city_started', table_name='discovery_runs')
    op.drop_table('discovery_runs')
    # ### end Alembic commands ###
