"""Initial schema: preferences, property_managers, strategies, listings, costs, feedback

Revision ID: a03ef5a832c6
Revises: 
Create Date: 2026-04-25 16:04:04.138924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a03ef5a832c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_component_timestamp', 'costs', ['component', 'timestamp'], unique=False)
    op.create_index(op.f('ix_costs_city'), 'costs', ['city'], unique=False)
    op.create_index(op.f('ix_costs_component'), 'costs', ['component'], unique=False)
    op.create_index(op.f('ix_costs_timestamp'), 'costs', ['timestamp'], unique=False)
    op.create_table('preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_city_created', 'preferences', ['city', 'created_at'], unique=False)
    op.create_index(op.f('ix_preferences_city'), 'preferences', ['city'], unique=False)
    op.create_table('property_managers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('listing_page_url', sa.Text(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('discovery_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_city_validated', 'property_managers', ['city', 'validated'], unique=False)
    op.create_index(op.f('ix_property_managers_city'), 'property_managers', ['city'], unique=False)
    op.create_table('extraction_strategies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_manager_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_json', sa.Text(), nullable=False),
    sa.Column('tier1_model', sa.String(length=100), nullable=True),
    sa.Column('tier2_model', sa.String(length=100), nullable=True),
    sa.Column('validation_rate', sa.Float(), nullable=False),
    sa.Column('last_refined', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_manager_id'], ['property_managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_manager_refined', 'extraction_strategies', ['property_manager_id', 'last_refined'], unique=False)
    op.create_index(op.f('ix_extraction_strategies_property_manager_id'), 'extraction_strategies', ['property_manager_id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_manager_id', sa.String(length=36), nullable=False),
    sa.Column('preference_id', sa.String(length=36), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('extraction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extraction_model', sa.String(length=100), nullable=True),
    sa.Column('tier1_cost', sa.Float(), nullable=True),
    sa.Column('tier2_cost', sa.Float(), nullable=True),
    sa.Column('validation_passed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['preference_id'], ['preferences.id'], ),
    sa.ForeignKeyConstraint(['property_manager_id'], ['property_managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_manager_timestamp', 'listings', ['property_manager_id', 'extraction_timestamp'], unique=False)
    op.create_index('idx_price', 'listings', ['price'], unique=False)
    op.create_index(op.f('ix_listings_preference_id'), 'listings', ['preference_id'], unique=False)
    op.create_index(op.f('ix_listings_property_manager_id'), 'listings', ['property_manager_id'], unique=False)
    op.create_table('extraction_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('strategy_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=True),
    sa.Column('validation_result', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('refined_strategy', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['extraction_strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strategy_timestamp', 'extraction_feedback', ['strategy_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_extraction_feedback_listing_id'), 'extraction_feedback', ['listing_id'], unique=False)
    op.create_index(op.f('ix_extraction_feedback_strategy_id'), 'extraction_feedback', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_extraction_feedback_timestamp'), 'extraction_feedback', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_feedback_timestamp'), table_name='extraction_feedback')
    op.drop_index(op.f('ix_extraction_feedback_strategy_id'), table_name='extraction_feedback')
    op.drop_index(op.f('ix_extraction_feedback_listing_id'), table_name='extraction_feedback')
    op.drop_index('idx_strategy_timestamp', table_name='extraction_feedback')
    op.drop_table('extraction_feedback')
    op.drop_index(op.f('ix_listings_property_manager_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_preference_id'), table_name='listings')
    op.drop_index('idx_price', table_name='listings')
    op.drop_index('idx_manager_timestamp', table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_extraction_strategies_property_manager_id'), table_name='extraction_strategies')
    op.drop_index('idx_manager_refined', table_name='extraction_strategies')
    op.drop_table('extraction_strategies')
    op.drop_index(op.f('ix_property_managers_city'), table_name='property_managers')
    op.drop_index('idx_city_validated', table_name='property_managers')
    op.drop_table('property_managers')
    op.drop_index(op.f('ix_preferences_city'), table_name='preferences')
    op.drop_index('idx_city_created', table_name='preferences')
    op.drop_table('preferences')
    op.drop_index(op.f('ix_costs_timestamp'), table_name='costs')
    op.drop_index(op.f('ix_costs_component'), table_name='costs')
    op.drop_index(op.f('ix_costs_city'), table_name='costs')
    op.drop_index('idx_component_timestamp', table_name='costs')
    op.drop_table('costs')
    # ### end Alembic commands ###
