"""add_listing_score_saved_fields

Revision ID: dd309f94683e
Revises: a03ef5a832c6
Create Date: 2026-04-25 17:11:16.605451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd309f94683e'
down_revision: Union[str, Sequence[str], None] = 'a03ef5a832c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('listings', sa.Column('score_explanation', sa.Text(), nullable=True))
    op.add_column('listings', sa.Column('saved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'saved')
    op.drop_column('listings', 'score_explanation')
    op.drop_column('listings', 'score')
    # ### end Alembic commands ###
