// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CityStatusApiDiscoveryCitiesCityStatusGetData, CityStatusApiDiscoveryCitiesCityStatusGetErrors, CityStatusApiDiscoveryCitiesCityStatusGetResponses, GetCostsApiCostsGetData, GetCostsApiCostsGetResponses, GetListingApiListingsListingIdGetData, GetListingApiListingsListingIdGetErrors, GetListingApiListingsListingIdGetResponses, GetListingsApiListingsGetData, GetListingsApiListingsGetErrors, GetListingsApiListingsGetResponses, GetMetricsMetricsGetData, GetMetricsMetricsGetResponses, HealthCheckHealthGetData, HealthCheckHealthGetResponses, ListManagersApiDiscoveryCitiesCityManagersGetData, ListManagersApiDiscoveryCitiesCityManagersGetErrors, ListManagersApiDiscoveryCitiesCityManagersGetResponses, RootGetData, RootGetResponses, StreamListingsApiListingsStreamGetData, StreamListingsApiListingsStreamGetResponses, ToggleSaveListingApiListingsListingIdSavePostData, ToggleSaveListingApiListingsListingIdSavePostErrors, ToggleSaveListingApiListingsListingIdSavePostResponses, TriggerDiscoveryApiDiscoveryCitiesCityPostData, TriggerDiscoveryApiDiscoveryCitiesCityPostErrors, TriggerDiscoveryApiDiscoveryCitiesCityPostResponses, TriggerExtractionExtractionTriggerPostData, TriggerExtractionExtractionTriggerPostErrors, TriggerExtractionExtractionTriggerPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Trigger Discovery
 *
 * Trigger a discovery run for the given city.
 */
export const triggerDiscoveryApiDiscoveryCitiesCityPost = <ThrowOnError extends boolean = false>(options: Options<TriggerDiscoveryApiDiscoveryCitiesCityPostData, ThrowOnError>) => (options.client ?? client).post<TriggerDiscoveryApiDiscoveryCitiesCityPostResponses, TriggerDiscoveryApiDiscoveryCitiesCityPostErrors, ThrowOnError>({
    url: '/api/discovery/cities/{city}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Managers
 *
 * List discovered managers for a city.
 */
export const listManagersApiDiscoveryCitiesCityManagersGet = <ThrowOnError extends boolean = false>(options: Options<ListManagersApiDiscoveryCitiesCityManagersGetData, ThrowOnError>) => (options.client ?? client).get<ListManagersApiDiscoveryCitiesCityManagersGetResponses, ListManagersApiDiscoveryCitiesCityManagersGetErrors, ThrowOnError>({ url: '/api/discovery/cities/{city}/managers', ...options });

/**
 * City Status
 *
 * Return discovery status for a city.
 */
export const cityStatusApiDiscoveryCitiesCityStatusGet = <ThrowOnError extends boolean = false>(options: Options<CityStatusApiDiscoveryCitiesCityStatusGetData, ThrowOnError>) => (options.client ?? client).get<CityStatusApiDiscoveryCitiesCityStatusGetResponses, CityStatusApiDiscoveryCitiesCityStatusGetErrors, ThrowOnError>({ url: '/api/discovery/cities/{city}/status', ...options });

/**
 * Trigger Extraction
 *
 * Trigger a manual extraction job.
 */
export const triggerExtractionExtractionTriggerPost = <ThrowOnError extends boolean = false>(options: Options<TriggerExtractionExtractionTriggerPostData, ThrowOnError>) => (options.client ?? client).post<TriggerExtractionExtractionTriggerPostResponses, TriggerExtractionExtractionTriggerPostErrors, ThrowOnError>({
    url: '/extraction/trigger',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Listings
 *
 * Return paginated, filterable listings.
 */
export const getListingsApiListingsGet = <ThrowOnError extends boolean = false>(options?: Options<GetListingsApiListingsGetData, ThrowOnError>) => (options?.client ?? client).get<GetListingsApiListingsGetResponses, GetListingsApiListingsGetErrors, ThrowOnError>({ url: '/api/listings', ...options });

/**
 * Get Listing
 *
 * Return a single listing by ID.
 */
export const getListingApiListingsListingIdGet = <ThrowOnError extends boolean = false>(options: Options<GetListingApiListingsListingIdGetData, ThrowOnError>) => (options.client ?? client).get<GetListingApiListingsListingIdGetResponses, GetListingApiListingsListingIdGetErrors, ThrowOnError>({ url: '/api/listings/{listing_id}', ...options });

/**
 * Toggle Save Listing
 *
 * Toggle the saved state of a listing.
 */
export const toggleSaveListingApiListingsListingIdSavePost = <ThrowOnError extends boolean = false>(options: Options<ToggleSaveListingApiListingsListingIdSavePostData, ThrowOnError>) => (options.client ?? client).post<ToggleSaveListingApiListingsListingIdSavePostResponses, ToggleSaveListingApiListingsListingIdSavePostErrors, ThrowOnError>({ url: '/api/listings/{listing_id}/save', ...options });

/**
 * Stream Listings
 *
 * SSE stream — push new listings as they arrive.
 */
export const streamListingsApiListingsStreamGet = <ThrowOnError extends boolean = false>(options?: Options<StreamListingsApiListingsStreamGetData, ThrowOnError>) => (options?.client ?? client).get<StreamListingsApiListingsStreamGetResponses, unknown, ThrowOnError>({ url: '/api/listings/stream', ...options });

/**
 * Health Check
 *
 * Health check endpoint.
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Root
 *
 * Root endpoint.
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Get Metrics
 *
 * Prometheus metrics endpoint.
 */
export const getMetricsMetricsGet = <ThrowOnError extends boolean = false>(options?: Options<GetMetricsMetricsGetData, ThrowOnError>) => (options?.client ?? client).get<GetMetricsMetricsGetResponses, unknown, ThrowOnError>({ url: '/metrics', ...options });

/**
 * Get Costs
 *
 * Get cost tracking summary.
 */
export const getCostsApiCostsGet = <ThrowOnError extends boolean = false>(options?: Options<GetCostsApiCostsGetData, ThrowOnError>) => (options?.client ?? client).get<GetCostsApiCostsGetResponses, unknown, ThrowOnError>({ url: '/api/costs', ...options });
