// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * CityStatus
 *
 * Discovery status for a city.
 */
export type CityStatus = {
    /**
     * City
     */
    city: string;
    /**
     * Has Been Discovered
     */
    has_been_discovered: boolean;
    /**
     * Managers Total
     */
    managers_total: number;
    /**
     * Managers Validated
     */
    managers_validated: number;
};

/**
 * DiscoveryResult
 *
 * Aggregate result of a city discovery run.
 */
export type DiscoveryResult = {
    /**
     * Cached
     */
    cached?: boolean;
    /**
     * Candidates Found
     */
    candidates_found: number;
    /**
     * City
     */
    city: string;
    /**
     * Cost Usd
     */
    cost_usd: number;
    /**
     * Duration Seconds
     */
    duration_seconds: number;
    /**
     * Validated Count
     */
    validated_count: number;
};

/**
 * ExtractionRequest
 */
export type ExtractionRequest = {
    /**
     * Html
     */
    html: string;
    /**
     * Property Manager Id
     */
    property_manager_id: string;
    /**
     * Url
     */
    url: string;
};

/**
 * ExtractionResponse
 */
export type ExtractionResponse = {
    /**
     * Confidence
     */
    confidence: 'high' | 'medium' | 'low';
    /**
     * Listing Address
     */
    listing_address: string;
    /**
     * Mode
     */
    mode: 'A' | 'B';
    /**
     * Status
     */
    status: 'success';
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ListingResponse
 *
 * Listing response model.
 */
export type ListingResponse = {
    /**
     * Address
     */
    address: string;
    /**
     * Amenities
     */
    amenities: Array<string>;
    /**
     * Bathrooms
     */
    bathrooms?: number | null;
    /**
     * Bedrooms
     */
    bedrooms?: number | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Extraction Model
     */
    extraction_model?: string | null;
    /**
     * Extraction Timestamp
     */
    extraction_timestamp: string;
    /**
     * Id
     */
    id: string;
    pets_policy: PetsPolicy;
    /**
     * Photos
     */
    photos: Array<string>;
    /**
     * Preference Id
     */
    preference_id?: string | null;
    /**
     * Price
     */
    price: number;
    /**
     * Property Manager Id
     */
    property_manager_id: string;
    /**
     * Saved
     */
    saved?: boolean;
    /**
     * Score
     */
    score?: number | null;
    /**
     * Score Explanation
     */
    score_explanation?: string | null;
    /**
     * Sqft
     */
    sqft?: number | null;
    /**
     * Tier1 Cost
     */
    tier1_cost?: number | null;
    /**
     * Tier2 Cost
     */
    tier2_cost?: number | null;
    /**
     * Url
     */
    url: string;
    /**
     * Validation Passed
     */
    validation_passed: boolean;
};

/**
 * ManagerOut
 *
 * Public representation of a discovered manager.
 */
export type ManagerOut = {
    /**
     * City
     */
    city: string;
    /**
     * Id
     */
    id: string;
    /**
     * Listing Page Url
     */
    listing_page_url: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Validated
     */
    validated: boolean;
    /**
     * Website
     */
    website: string | null;
};

/**
 * PetsPolicy
 */
export type PetsPolicy = 'allowed_with_small_dog' | 'cats_only' | 'none_allowed' | 'unknown';

/**
 * PreferenceCreate
 *
 * Create a new preference.
 */
export type PreferenceCreate = {
    /**
     * City
     */
    city: string;
    /**
     * Description
     */
    description: string;
};

/**
 * PreferenceResponse
 *
 * Preference response model.
 */
export type PreferenceResponse = {
    /**
     * City
     */
    city: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Description
     */
    description: string;
    /**
     * Id
     */
    id: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PreferenceUpdate
 *
 * Update an existing preference.
 */
export type PreferenceUpdate = {
    /**
     * City
     */
    city?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ScoreListingsRequest
 *
 * Run preference scoring for persisted listings.
 */
export type ScoreListingsRequest = {
    /**
     * Limit
     */
    limit?: number;
    /**
     * Listing Ids
     */
    listing_ids?: Array<string>;
    /**
     * Preference Id
     */
    preference_id: string;
    /**
     * Rescore
     */
    rescore?: boolean;
};

/**
 * ScoreListingsResponse
 *
 * Summary of a listing scoring run.
 */
export type ScoreListingsResponse = {
    /**
     * Listing Ids
     */
    listing_ids: Array<string>;
    /**
     * Preference Id
     */
    preference_id: string;
    /**
     * Scored Count
     */
    scored_count: number;
};

/**
 * TriggerRequest
 *
 * Optional body for POST trigger.
 */
export type TriggerRequest = {
    /**
     * Preference Id
     */
    preference_id?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Response Root  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type RootGetResponse = RootGetResponses[keyof RootGetResponses];

export type GetCostsApiCostsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/costs';
};

export type GetCostsApiCostsGetResponses = {
    /**
     * Response Get Costs Api Costs Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetCostsApiCostsGetResponse = GetCostsApiCostsGetResponses[keyof GetCostsApiCostsGetResponses];

export type TriggerDiscoveryApiDiscoveryCitiesCityPostData = {
    /**
     * Body
     */
    body?: TriggerRequest | null;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * City
         */
        city: string;
    };
    query?: never;
    url: '/api/discovery/cities/{city}';
};

export type TriggerDiscoveryApiDiscoveryCitiesCityPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerDiscoveryApiDiscoveryCitiesCityPostError = TriggerDiscoveryApiDiscoveryCitiesCityPostErrors[keyof TriggerDiscoveryApiDiscoveryCitiesCityPostErrors];

export type TriggerDiscoveryApiDiscoveryCitiesCityPostResponses = {
    /**
     * Successful Response
     */
    200: DiscoveryResult;
};

export type TriggerDiscoveryApiDiscoveryCitiesCityPostResponse = TriggerDiscoveryApiDiscoveryCitiesCityPostResponses[keyof TriggerDiscoveryApiDiscoveryCitiesCityPostResponses];

export type ListManagersApiDiscoveryCitiesCityManagersGetData = {
    body?: never;
    path: {
        /**
         * City
         */
        city: string;
    };
    query?: never;
    url: '/api/discovery/cities/{city}/managers';
};

export type ListManagersApiDiscoveryCitiesCityManagersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListManagersApiDiscoveryCitiesCityManagersGetError = ListManagersApiDiscoveryCitiesCityManagersGetErrors[keyof ListManagersApiDiscoveryCitiesCityManagersGetErrors];

export type ListManagersApiDiscoveryCitiesCityManagersGetResponses = {
    /**
     * Response List Managers Api Discovery Cities  City  Managers Get
     *
     * Successful Response
     */
    200: Array<ManagerOut>;
};

export type ListManagersApiDiscoveryCitiesCityManagersGetResponse = ListManagersApiDiscoveryCitiesCityManagersGetResponses[keyof ListManagersApiDiscoveryCitiesCityManagersGetResponses];

export type CityStatusApiDiscoveryCitiesCityStatusGetData = {
    body?: never;
    path: {
        /**
         * City
         */
        city: string;
    };
    query?: never;
    url: '/api/discovery/cities/{city}/status';
};

export type CityStatusApiDiscoveryCitiesCityStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CityStatusApiDiscoveryCitiesCityStatusGetError = CityStatusApiDiscoveryCitiesCityStatusGetErrors[keyof CityStatusApiDiscoveryCitiesCityStatusGetErrors];

export type CityStatusApiDiscoveryCitiesCityStatusGetResponses = {
    /**
     * Successful Response
     */
    200: CityStatus;
};

export type CityStatusApiDiscoveryCitiesCityStatusGetResponse = CityStatusApiDiscoveryCitiesCityStatusGetResponses[keyof CityStatusApiDiscoveryCitiesCityStatusGetResponses];

export type GetListingsApiListingsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * City
         */
        city?: string | null;
        /**
         * Min Price
         */
        min_price?: number | null;
        /**
         * Max Price
         */
        max_price?: number | null;
        /**
         * Min Bedrooms
         */
        min_bedrooms?: number | null;
        /**
         * Max Bedrooms
         */
        max_bedrooms?: number | null;
        /**
         * Saved Only
         */
        saved_only?: boolean;
        /**
         * Min Score
         */
        min_score?: number | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/listings';
};

export type GetListingsApiListingsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetListingsApiListingsGetError = GetListingsApiListingsGetErrors[keyof GetListingsApiListingsGetErrors];

export type GetListingsApiListingsGetResponses = {
    /**
     * Response Get Listings Api Listings Get
     *
     * Successful Response
     */
    200: Array<ListingResponse>;
};

export type GetListingsApiListingsGetResponse = GetListingsApiListingsGetResponses[keyof GetListingsApiListingsGetResponses];

export type ScoreListingsApiListingsScorePostData = {
    body: ScoreListingsRequest;
    path?: never;
    query?: never;
    url: '/api/listings/score';
};

export type ScoreListingsApiListingsScorePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScoreListingsApiListingsScorePostError = ScoreListingsApiListingsScorePostErrors[keyof ScoreListingsApiListingsScorePostErrors];

export type ScoreListingsApiListingsScorePostResponses = {
    /**
     * Successful Response
     */
    200: ScoreListingsResponse;
};

export type ScoreListingsApiListingsScorePostResponse = ScoreListingsApiListingsScorePostResponses[keyof ScoreListingsApiListingsScorePostResponses];

export type StreamListingsApiListingsStreamGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/listings/stream';
};

export type StreamListingsApiListingsStreamGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetListingApiListingsListingIdGetData = {
    body?: never;
    path: {
        /**
         * Listing Id
         */
        listing_id: string;
    };
    query?: never;
    url: '/api/listings/{listing_id}';
};

export type GetListingApiListingsListingIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetListingApiListingsListingIdGetError = GetListingApiListingsListingIdGetErrors[keyof GetListingApiListingsListingIdGetErrors];

export type GetListingApiListingsListingIdGetResponses = {
    /**
     * Successful Response
     */
    200: ListingResponse;
};

export type GetListingApiListingsListingIdGetResponse = GetListingApiListingsListingIdGetResponses[keyof GetListingApiListingsListingIdGetResponses];

export type ToggleSaveListingApiListingsListingIdSavePostData = {
    body?: never;
    path: {
        /**
         * Listing Id
         */
        listing_id: string;
    };
    query?: never;
    url: '/api/listings/{listing_id}/save';
};

export type ToggleSaveListingApiListingsListingIdSavePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ToggleSaveListingApiListingsListingIdSavePostError = ToggleSaveListingApiListingsListingIdSavePostErrors[keyof ToggleSaveListingApiListingsListingIdSavePostErrors];

export type ToggleSaveListingApiListingsListingIdSavePostResponses = {
    /**
     * Successful Response
     */
    200: ListingResponse;
};

export type ToggleSaveListingApiListingsListingIdSavePostResponse = ToggleSaveListingApiListingsListingIdSavePostResponses[keyof ToggleSaveListingApiListingsListingIdSavePostResponses];

export type ListPreferencesApiPreferencesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/preferences';
};

export type ListPreferencesApiPreferencesGetResponses = {
    /**
     * Response List Preferences Api Preferences Get
     *
     * Successful Response
     */
    200: Array<PreferenceResponse>;
};

export type ListPreferencesApiPreferencesGetResponse = ListPreferencesApiPreferencesGetResponses[keyof ListPreferencesApiPreferencesGetResponses];

export type CreatePreferenceApiPreferencesPostData = {
    body: PreferenceCreate;
    path?: never;
    query?: never;
    url: '/api/preferences';
};

export type CreatePreferenceApiPreferencesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePreferenceApiPreferencesPostError = CreatePreferenceApiPreferencesPostErrors[keyof CreatePreferenceApiPreferencesPostErrors];

export type CreatePreferenceApiPreferencesPostResponses = {
    /**
     * Successful Response
     */
    201: PreferenceResponse;
};

export type CreatePreferenceApiPreferencesPostResponse = CreatePreferenceApiPreferencesPostResponses[keyof CreatePreferenceApiPreferencesPostResponses];

export type DeletePreferenceApiPreferencesPreferenceIdDeleteData = {
    body?: never;
    path: {
        /**
         * Preference Id
         */
        preference_id: string;
    };
    query?: never;
    url: '/api/preferences/{preference_id}';
};

export type DeletePreferenceApiPreferencesPreferenceIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePreferenceApiPreferencesPreferenceIdDeleteError = DeletePreferenceApiPreferencesPreferenceIdDeleteErrors[keyof DeletePreferenceApiPreferencesPreferenceIdDeleteErrors];

export type DeletePreferenceApiPreferencesPreferenceIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePreferenceApiPreferencesPreferenceIdDeleteResponse = DeletePreferenceApiPreferencesPreferenceIdDeleteResponses[keyof DeletePreferenceApiPreferencesPreferenceIdDeleteResponses];

export type UpdatePreferenceApiPreferencesPreferenceIdPatchData = {
    body: PreferenceUpdate;
    path: {
        /**
         * Preference Id
         */
        preference_id: string;
    };
    query?: never;
    url: '/api/preferences/{preference_id}';
};

export type UpdatePreferenceApiPreferencesPreferenceIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePreferenceApiPreferencesPreferenceIdPatchError = UpdatePreferenceApiPreferencesPreferenceIdPatchErrors[keyof UpdatePreferenceApiPreferencesPreferenceIdPatchErrors];

export type UpdatePreferenceApiPreferencesPreferenceIdPatchResponses = {
    /**
     * Successful Response
     */
    200: PreferenceResponse;
};

export type UpdatePreferenceApiPreferencesPreferenceIdPatchResponse = UpdatePreferenceApiPreferencesPreferenceIdPatchResponses[keyof UpdatePreferenceApiPreferencesPreferenceIdPatchResponses];

export type TriggerExtractionExtractionTriggerPostData = {
    body: ExtractionRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/extraction/trigger';
};

export type TriggerExtractionExtractionTriggerPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerExtractionExtractionTriggerPostError = TriggerExtractionExtractionTriggerPostErrors[keyof TriggerExtractionExtractionTriggerPostErrors];

export type TriggerExtractionExtractionTriggerPostResponses = {
    /**
     * Successful Response
     */
    200: ExtractionResponse;
};

export type TriggerExtractionExtractionTriggerPostResponse = TriggerExtractionExtractionTriggerPostResponses[keyof TriggerExtractionExtractionTriggerPostResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Response Health Check Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthCheckHealthGetResponse = HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];

export type GetMetricsMetricsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/metrics';
};

export type GetMetricsMetricsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
