// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * CityStatus
 */
export type CityStatus = {
    /**
     * City
     */
    city: string;
    /**
     * Managers Total
     */
    managers_total: number;
    /**
     * Managers Validated
     */
    managers_validated: number;
    /**
     * Has Been Discovered
     */
    has_been_discovered: boolean;
};

/**
 * CostGroupedEntry
 *
 * A cost entry grouped by a dimension (component, model, city).
 */
export type CostGroupedEntry = {
    /**
     * Group
     */
    group: string;
    /**
     * Cost Usd
     */
    cost_usd: number;
    /**
     * Call Count
     */
    call_count: number;
    /**
     * Tokens Total
     */
    tokens_total: number;
};

/**
 * CostResponse
 *
 * Cost tracking response model.
 */
export type CostResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Component
     */
    component: string;
    /**
     * Model
     */
    model: string;
    /**
     * Tokens In
     */
    tokens_in: number;
    /**
     * Tokens Out
     */
    tokens_out: number;
    /**
     * Cost Usd
     */
    cost_usd: number;
    /**
     * Cache Hit
     */
    cache_hit: boolean;
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * City
     */
    city?: string | null;
};

/**
 * CostSummaryResponse
 *
 * Full cost summary with budget info.
 */
export type CostSummaryResponse = {
    /**
     * Total Cost Usd
     */
    total_cost_usd: number;
    /**
     * Total Calls
     */
    total_calls: number;
    /**
     * Total Tokens
     */
    total_tokens: number;
    /**
     * Avg Cost Per Call
     */
    avg_cost_per_call: number;
    /**
     * Cache Hit Rate
     */
    cache_hit_rate: number;
    /**
     * Budget Limit Usd
     */
    budget_limit_usd: number;
    /**
     * Budget Remaining Usd
     */
    budget_remaining_usd: number;
    /**
     * Budget Exceeded
     */
    budget_exceeded: boolean;
};

/**
 * CostTimeseriesPoint
 *
 * A single data point for cost timeseries charts.
 */
export type CostTimeseriesPoint = {
    /**
     * Date
     */
    date: string;
    /**
     * Cost Usd
     */
    cost_usd: number;
    /**
     * Call Count
     */
    call_count: number;
    /**
     * Tokens Total
     */
    tokens_total: number;
};

/**
 * DiscoveryResult
 *
 * Aggregate result of a city discovery run.
 */
export type DiscoveryResult = {
    /**
     * City
     */
    city: string;
    /**
     * Candidates Found
     */
    candidates_found: number;
    /**
     * Validated Count
     */
    validated_count: number;
    /**
     * Cached
     */
    cached?: boolean;
    /**
     * Cost Usd
     */
    cost_usd: number;
    /**
     * Duration Seconds
     */
    duration_seconds: number;
};

/**
 * DiscoveryRunLogResponse
 */
export type DiscoveryRunLogResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Sequence
     */
    sequence: number;
    /**
     * Level
     */
    level: string;
    /**
     * Component
     */
    component: string;
    /**
     * Message
     */
    message: string;
    /**
     * Details
     */
    details?: string | null;
    /**
     * Timestamp
     */
    timestamp: string;
};

/**
 * DiscoveryRunResponse
 */
export type DiscoveryRunResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * City
     */
    city: string;
    /**
     * Preference Id
     */
    preference_id?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Managers Found
     */
    managers_found?: number | null;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Finished At
     */
    finished_at?: string | null;
    /**
     * Logs
     */
    logs?: Array<DiscoveryRunLogResponse>;
};

/**
 * ExtractionRequest
 */
export type ExtractionRequest = {
    /**
     * Property Manager Id
     */
    property_manager_id: string;
    /**
     * Preference Id
     */
    preference_id?: string | null;
    /**
     * Url
     */
    url: string;
    /**
     * Html
     */
    html: string;
};

/**
 * ExtractionResponse
 */
export type ExtractionResponse = {
    /**
     * Status
     */
    status: 'success';
    /**
     * Confidence
     */
    confidence: 'high' | 'medium' | 'low';
    /**
     * Mode
     */
    mode: 'A' | 'B';
    /**
     * Listing Address
     */
    listing_address: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ListingResponse
 *
 * Listing response model.
 */
export type ListingResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Property Manager Id
     */
    property_manager_id: string;
    /**
     * Preference Id
     */
    preference_id?: string | null;
    /**
     * Address
     */
    address: string;
    /**
     * Bedrooms
     */
    bedrooms?: number | null;
    /**
     * Bathrooms
     */
    bathrooms?: number | null;
    /**
     * Sqft
     */
    sqft?: number | null;
    /**
     * Price
     */
    price: number;
    /**
     * Url
     */
    url: string;
    pets_policy: PetsPolicy;
    /**
     * Amenities
     */
    amenities: Array<string>;
    /**
     * Photos
     */
    photos: Array<string>;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Extraction Timestamp
     */
    extraction_timestamp: string;
    /**
     * Extraction Model
     */
    extraction_model?: string | null;
    /**
     * Tier1 Cost
     */
    tier1_cost?: number | null;
    /**
     * Tier2 Cost
     */
    tier2_cost?: number | null;
    /**
     * Validation Passed
     */
    validation_passed: boolean;
    /**
     * Score
     */
    score?: number | null;
    /**
     * Score Explanation
     */
    score_explanation?: string | null;
    /**
     * Saved
     */
    saved?: boolean;
};

/**
 * ManagerOut
 */
export type ManagerOut = {
    /**
     * Id
     */
    id: string;
    /**
     * City
     */
    city: string;
    /**
     * Name
     */
    name: string;
    /**
     * Website
     */
    website: string | null;
    /**
     * Listing Page Url
     */
    listing_page_url: string | null;
    /**
     * Validated
     */
    validated: boolean;
};

/**
 * ModelInfo
 */
export type ModelInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Provider
     */
    provider: string;
    /**
     * Context Length
     */
    context_length: number;
    /**
     * Prompt Price
     */
    prompt_price: number;
    /**
     * Completion Price
     */
    completion_price: number;
};

/**
 * ModelsRequest
 *
 * Request available OpenRouter models without putting secrets in URLs.
 */
export type ModelsRequest = {
    /**
     * Key
     */
    key?: string | null;
    /**
     * Preference Id
     */
    preference_id?: string | null;
    /**
     * Curated
     */
    curated?: boolean;
};

/**
 * PetsPolicy
 */
export type PetsPolicy = 'allowed_with_small_dog' | 'cats_only' | 'none_allowed' | 'unknown';

/**
 * PreferenceCreate
 *
 * Create a new preference.
 */
export type PreferenceCreate = {
    /**
     * Description
     */
    description: string;
    /**
     * City
     */
    city: string;
    /**
     * Api Provider
     */
    api_provider?: string;
    /**
     * Openrouter Api Key
     */
    openrouter_api_key?: string | null;
    /**
     * Apify Api Token
     */
    apify_api_token?: string | null;
    /**
     * Fast Model
     */
    fast_model?: string | null;
    /**
     * Smart Model
     */
    smart_model?: string | null;
};

/**
 * PreferenceResponse
 *
 * Preference response model.
 */
export type PreferenceResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Description
     */
    description: string;
    /**
     * City
     */
    city: string;
    /**
     * Api Provider
     */
    api_provider: string;
    /**
     * Has Openrouter Api Key
     */
    has_openrouter_api_key?: boolean;
    /**
     * Openrouter Key Last4
     */
    openrouter_key_last4?: string | null;
    /**
     * Has Apify Api Token
     */
    has_apify_api_token?: boolean;
    /**
     * Apify Token Last4
     */
    apify_token_last4?: string | null;
    /**
     * Fast Model
     */
    fast_model?: string | null;
    /**
     * Smart Model
     */
    smart_model?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PreferenceUpdate
 *
 * Update an existing preference.
 */
export type PreferenceUpdate = {
    /**
     * Description
     */
    description?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * Api Provider
     */
    api_provider?: string | null;
    /**
     * Openrouter Api Key
     */
    openrouter_api_key?: string | null;
    /**
     * Apify Api Token
     */
    apify_api_token?: string | null;
    /**
     * Fast Model
     */
    fast_model?: string | null;
    /**
     * Smart Model
     */
    smart_model?: string | null;
};

/**
 * ScoreListingsRequest
 *
 * Run preference scoring for persisted listings.
 */
export type ScoreListingsRequest = {
    /**
     * Preference Id
     */
    preference_id: string;
    /**
     * Listing Ids
     */
    listing_ids?: Array<string>;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Rescore
     */
    rescore?: boolean;
};

/**
 * ScoreListingsResponse
 *
 * Summary of a listing scoring run.
 */
export type ScoreListingsResponse = {
    /**
     * Preference Id
     */
    preference_id: string;
    /**
     * Scored Count
     */
    scored_count: number;
    /**
     * Listing Ids
     */
    listing_ids: Array<string>;
};

/**
 * TriggerRequest
 */
export type TriggerRequest = {
    /**
     * City
     */
    city: string;
    /**
     * Preference Id
     */
    preference_id?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListCostsApiCostsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Start
         *
         * ISO start date
         */
        start?: string | null;
        /**
         * End
         *
         * ISO end date
         */
        end?: string | null;
        /**
         * Component
         */
        component?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/costs';
};

export type ListCostsApiCostsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListCostsApiCostsGetError = ListCostsApiCostsGetErrors[keyof ListCostsApiCostsGetErrors];

export type ListCostsApiCostsGetResponses = {
    /**
     * Response List Costs Api Costs Get
     *
     * Successful Response
     */
    200: Array<CostResponse>;
};

export type ListCostsApiCostsGetResponse = ListCostsApiCostsGetResponses[keyof ListCostsApiCostsGetResponses];

export type CostSummaryApiCostsSummaryGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Start
         */
        start?: string | null;
        /**
         * End
         */
        end?: string | null;
    };
    url: '/api/costs/summary';
};

export type CostSummaryApiCostsSummaryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CostSummaryApiCostsSummaryGetError = CostSummaryApiCostsSummaryGetErrors[keyof CostSummaryApiCostsSummaryGetErrors];

export type CostSummaryApiCostsSummaryGetResponses = {
    /**
     * Successful Response
     */
    200: CostSummaryResponse;
};

export type CostSummaryApiCostsSummaryGetResponse = CostSummaryApiCostsSummaryGetResponses[keyof CostSummaryApiCostsSummaryGetResponses];

export type CostsByComponentApiCostsByComponentGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Start
         */
        start?: string | null;
        /**
         * End
         */
        end?: string | null;
    };
    url: '/api/costs/by-component';
};

export type CostsByComponentApiCostsByComponentGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CostsByComponentApiCostsByComponentGetError = CostsByComponentApiCostsByComponentGetErrors[keyof CostsByComponentApiCostsByComponentGetErrors];

export type CostsByComponentApiCostsByComponentGetResponses = {
    /**
     * Response Costs By Component Api Costs By Component Get
     *
     * Successful Response
     */
    200: Array<CostGroupedEntry>;
};

export type CostsByComponentApiCostsByComponentGetResponse = CostsByComponentApiCostsByComponentGetResponses[keyof CostsByComponentApiCostsByComponentGetResponses];

export type CostsByModelApiCostsByModelGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Start
         */
        start?: string | null;
        /**
         * End
         */
        end?: string | null;
    };
    url: '/api/costs/by-model';
};

export type CostsByModelApiCostsByModelGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CostsByModelApiCostsByModelGetError = CostsByModelApiCostsByModelGetErrors[keyof CostsByModelApiCostsByModelGetErrors];

export type CostsByModelApiCostsByModelGetResponses = {
    /**
     * Response Costs By Model Api Costs By Model Get
     *
     * Successful Response
     */
    200: Array<CostGroupedEntry>;
};

export type CostsByModelApiCostsByModelGetResponse = CostsByModelApiCostsByModelGetResponses[keyof CostsByModelApiCostsByModelGetResponses];

export type CostsByCityApiCostsByCityGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Start
         */
        start?: string | null;
        /**
         * End
         */
        end?: string | null;
    };
    url: '/api/costs/by-city';
};

export type CostsByCityApiCostsByCityGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CostsByCityApiCostsByCityGetError = CostsByCityApiCostsByCityGetErrors[keyof CostsByCityApiCostsByCityGetErrors];

export type CostsByCityApiCostsByCityGetResponses = {
    /**
     * Response Costs By City Api Costs By City Get
     *
     * Successful Response
     */
    200: Array<CostGroupedEntry>;
};

export type CostsByCityApiCostsByCityGetResponse = CostsByCityApiCostsByCityGetResponses[keyof CostsByCityApiCostsByCityGetResponses];

export type CostsTimeseriesApiCostsTimeseriesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Days
         */
        days?: number;
    };
    url: '/api/costs/timeseries';
};

export type CostsTimeseriesApiCostsTimeseriesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CostsTimeseriesApiCostsTimeseriesGetError = CostsTimeseriesApiCostsTimeseriesGetErrors[keyof CostsTimeseriesApiCostsTimeseriesGetErrors];

export type CostsTimeseriesApiCostsTimeseriesGetResponses = {
    /**
     * Response Costs Timeseries Api Costs Timeseries Get
     *
     * Successful Response
     */
    200: Array<CostTimeseriesPoint>;
};

export type CostsTimeseriesApiCostsTimeseriesGetResponse = CostsTimeseriesApiCostsTimeseriesGetResponses[keyof CostsTimeseriesApiCostsTimeseriesGetResponses];

export type TriggerDiscoveryV2ApiDiscoveryTriggerPostData = {
    body: TriggerRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/discovery/trigger';
};

export type TriggerDiscoveryV2ApiDiscoveryTriggerPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerDiscoveryV2ApiDiscoveryTriggerPostError = TriggerDiscoveryV2ApiDiscoveryTriggerPostErrors[keyof TriggerDiscoveryV2ApiDiscoveryTriggerPostErrors];

export type TriggerDiscoveryV2ApiDiscoveryTriggerPostResponses = {
    /**
     * Successful Response
     */
    200: DiscoveryRunResponse;
};

export type TriggerDiscoveryV2ApiDiscoveryTriggerPostResponse = TriggerDiscoveryV2ApiDiscoveryTriggerPostResponses[keyof TriggerDiscoveryV2ApiDiscoveryTriggerPostResponses];

export type ListRunsApiDiscoveryRunsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/discovery/runs';
};

export type ListRunsApiDiscoveryRunsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRunsApiDiscoveryRunsGetError = ListRunsApiDiscoveryRunsGetErrors[keyof ListRunsApiDiscoveryRunsGetErrors];

export type ListRunsApiDiscoveryRunsGetResponses = {
    /**
     * Response List Runs Api Discovery Runs Get
     *
     * Successful Response
     */
    200: Array<DiscoveryRunResponse>;
};

export type ListRunsApiDiscoveryRunsGetResponse = ListRunsApiDiscoveryRunsGetResponses[keyof ListRunsApiDiscoveryRunsGetResponses];

export type GetRunApiDiscoveryRunsRunIdGetData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/discovery/runs/{run_id}';
};

export type GetRunApiDiscoveryRunsRunIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRunApiDiscoveryRunsRunIdGetError = GetRunApiDiscoveryRunsRunIdGetErrors[keyof GetRunApiDiscoveryRunsRunIdGetErrors];

export type GetRunApiDiscoveryRunsRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: DiscoveryRunResponse;
};

export type GetRunApiDiscoveryRunsRunIdGetResponse = GetRunApiDiscoveryRunsRunIdGetResponses[keyof GetRunApiDiscoveryRunsRunIdGetResponses];

export type TriggerDiscoveryApiDiscoveryCitiesCityPostData = {
    /**
     * Body
     */
    body?: TriggerRequest | null;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * City
         */
        city: string;
    };
    query?: never;
    url: '/api/discovery/cities/{city}';
};

export type TriggerDiscoveryApiDiscoveryCitiesCityPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerDiscoveryApiDiscoveryCitiesCityPostError = TriggerDiscoveryApiDiscoveryCitiesCityPostErrors[keyof TriggerDiscoveryApiDiscoveryCitiesCityPostErrors];

export type TriggerDiscoveryApiDiscoveryCitiesCityPostResponses = {
    /**
     * Successful Response
     */
    200: DiscoveryResult;
};

export type TriggerDiscoveryApiDiscoveryCitiesCityPostResponse = TriggerDiscoveryApiDiscoveryCitiesCityPostResponses[keyof TriggerDiscoveryApiDiscoveryCitiesCityPostResponses];

export type ListManagersApiDiscoveryCitiesCityManagersGetData = {
    body?: never;
    path: {
        /**
         * City
         */
        city: string;
    };
    query?: never;
    url: '/api/discovery/cities/{city}/managers';
};

export type ListManagersApiDiscoveryCitiesCityManagersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListManagersApiDiscoveryCitiesCityManagersGetError = ListManagersApiDiscoveryCitiesCityManagersGetErrors[keyof ListManagersApiDiscoveryCitiesCityManagersGetErrors];

export type ListManagersApiDiscoveryCitiesCityManagersGetResponses = {
    /**
     * Response List Managers Api Discovery Cities  City  Managers Get
     *
     * Successful Response
     */
    200: Array<ManagerOut>;
};

export type ListManagersApiDiscoveryCitiesCityManagersGetResponse = ListManagersApiDiscoveryCitiesCityManagersGetResponses[keyof ListManagersApiDiscoveryCitiesCityManagersGetResponses];

export type CityStatusApiDiscoveryCitiesCityStatusGetData = {
    body?: never;
    path: {
        /**
         * City
         */
        city: string;
    };
    query?: never;
    url: '/api/discovery/cities/{city}/status';
};

export type CityStatusApiDiscoveryCitiesCityStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CityStatusApiDiscoveryCitiesCityStatusGetError = CityStatusApiDiscoveryCitiesCityStatusGetErrors[keyof CityStatusApiDiscoveryCitiesCityStatusGetErrors];

export type CityStatusApiDiscoveryCitiesCityStatusGetResponses = {
    /**
     * Successful Response
     */
    200: CityStatus;
};

export type CityStatusApiDiscoveryCitiesCityStatusGetResponse = CityStatusApiDiscoveryCitiesCityStatusGetResponses[keyof CityStatusApiDiscoveryCitiesCityStatusGetResponses];

export type TriggerExtractionExtractionTriggerPostData = {
    body: ExtractionRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/extraction/trigger';
};

export type TriggerExtractionExtractionTriggerPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TriggerExtractionExtractionTriggerPostError = TriggerExtractionExtractionTriggerPostErrors[keyof TriggerExtractionExtractionTriggerPostErrors];

export type TriggerExtractionExtractionTriggerPostResponses = {
    /**
     * Successful Response
     */
    200: ExtractionResponse;
};

export type TriggerExtractionExtractionTriggerPostResponse = TriggerExtractionExtractionTriggerPostResponses[keyof TriggerExtractionExtractionTriggerPostResponses];

export type GetListingsApiListingsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * City
         */
        city?: string | null;
        /**
         * Min Price
         */
        min_price?: number | null;
        /**
         * Max Price
         */
        max_price?: number | null;
        /**
         * Min Bedrooms
         */
        min_bedrooms?: number | null;
        /**
         * Max Bedrooms
         */
        max_bedrooms?: number | null;
        /**
         * Saved Only
         */
        saved_only?: boolean;
        /**
         * Min Score
         */
        min_score?: number | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/listings';
};

export type GetListingsApiListingsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetListingsApiListingsGetError = GetListingsApiListingsGetErrors[keyof GetListingsApiListingsGetErrors];

export type GetListingsApiListingsGetResponses = {
    /**
     * Response Get Listings Api Listings Get
     *
     * Successful Response
     */
    200: Array<ListingResponse>;
};

export type GetListingsApiListingsGetResponse = GetListingsApiListingsGetResponses[keyof GetListingsApiListingsGetResponses];

export type StreamListingsApiListingsStreamGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/listings/stream';
};

export type StreamListingsApiListingsStreamGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamListingsApiListingsStreamGetError = StreamListingsApiListingsStreamGetErrors[keyof StreamListingsApiListingsStreamGetErrors];

export type StreamListingsApiListingsStreamGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ScoreListingsApiListingsScorePostData = {
    body: ScoreListingsRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/listings/score';
};

export type ScoreListingsApiListingsScorePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScoreListingsApiListingsScorePostError = ScoreListingsApiListingsScorePostErrors[keyof ScoreListingsApiListingsScorePostErrors];

export type ScoreListingsApiListingsScorePostResponses = {
    /**
     * Successful Response
     */
    200: ScoreListingsResponse;
};

export type ScoreListingsApiListingsScorePostResponse = ScoreListingsApiListingsScorePostResponses[keyof ScoreListingsApiListingsScorePostResponses];

export type GetListingApiListingsListingIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Listing Id
         */
        listing_id: string;
    };
    query?: never;
    url: '/api/listings/{listing_id}';
};

export type GetListingApiListingsListingIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetListingApiListingsListingIdGetError = GetListingApiListingsListingIdGetErrors[keyof GetListingApiListingsListingIdGetErrors];

export type GetListingApiListingsListingIdGetResponses = {
    /**
     * Successful Response
     */
    200: ListingResponse;
};

export type GetListingApiListingsListingIdGetResponse = GetListingApiListingsListingIdGetResponses[keyof GetListingApiListingsListingIdGetResponses];

export type ToggleSaveListingApiListingsListingIdSavePostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Listing Id
         */
        listing_id: string;
    };
    query?: never;
    url: '/api/listings/{listing_id}/save';
};

export type ToggleSaveListingApiListingsListingIdSavePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ToggleSaveListingApiListingsListingIdSavePostError = ToggleSaveListingApiListingsListingIdSavePostErrors[keyof ToggleSaveListingApiListingsListingIdSavePostErrors];

export type ToggleSaveListingApiListingsListingIdSavePostResponses = {
    /**
     * Successful Response
     */
    200: ListingResponse;
};

export type ToggleSaveListingApiListingsListingIdSavePostResponse = ToggleSaveListingApiListingsListingIdSavePostResponses[keyof ToggleSaveListingApiListingsListingIdSavePostResponses];

export type ListPreferencesApiPreferencesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/preferences';
};

export type ListPreferencesApiPreferencesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPreferencesApiPreferencesGetError = ListPreferencesApiPreferencesGetErrors[keyof ListPreferencesApiPreferencesGetErrors];

export type ListPreferencesApiPreferencesGetResponses = {
    /**
     * Response List Preferences Api Preferences Get
     *
     * Successful Response
     */
    200: Array<PreferenceResponse>;
};

export type ListPreferencesApiPreferencesGetResponse = ListPreferencesApiPreferencesGetResponses[keyof ListPreferencesApiPreferencesGetResponses];

export type CreatePreferenceApiPreferencesPostData = {
    body: PreferenceCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/preferences';
};

export type CreatePreferenceApiPreferencesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePreferenceApiPreferencesPostError = CreatePreferenceApiPreferencesPostErrors[keyof CreatePreferenceApiPreferencesPostErrors];

export type CreatePreferenceApiPreferencesPostResponses = {
    /**
     * Successful Response
     */
    201: PreferenceResponse;
};

export type CreatePreferenceApiPreferencesPostResponse = CreatePreferenceApiPreferencesPostResponses[keyof CreatePreferenceApiPreferencesPostResponses];

export type DeletePreferenceApiPreferencesPreferenceIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Preference Id
         */
        preference_id: string;
    };
    query?: never;
    url: '/api/preferences/{preference_id}';
};

export type DeletePreferenceApiPreferencesPreferenceIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePreferenceApiPreferencesPreferenceIdDeleteError = DeletePreferenceApiPreferencesPreferenceIdDeleteErrors[keyof DeletePreferenceApiPreferencesPreferenceIdDeleteErrors];

export type DeletePreferenceApiPreferencesPreferenceIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePreferenceApiPreferencesPreferenceIdDeleteResponse = DeletePreferenceApiPreferencesPreferenceIdDeleteResponses[keyof DeletePreferenceApiPreferencesPreferenceIdDeleteResponses];

export type UpdatePreferenceApiPreferencesPreferenceIdPatchData = {
    body: PreferenceUpdate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Preference Id
         */
        preference_id: string;
    };
    query?: never;
    url: '/api/preferences/{preference_id}';
};

export type UpdatePreferenceApiPreferencesPreferenceIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePreferenceApiPreferencesPreferenceIdPatchError = UpdatePreferenceApiPreferencesPreferenceIdPatchErrors[keyof UpdatePreferenceApiPreferencesPreferenceIdPatchErrors];

export type UpdatePreferenceApiPreferencesPreferenceIdPatchResponses = {
    /**
     * Successful Response
     */
    200: PreferenceResponse;
};

export type UpdatePreferenceApiPreferencesPreferenceIdPatchResponse = UpdatePreferenceApiPreferencesPreferenceIdPatchResponses[keyof UpdatePreferenceApiPreferencesPreferenceIdPatchResponses];

export type ListModelsApiOpenrouterModelsPostData = {
    body: ModelsRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/openrouter/models';
};

export type ListModelsApiOpenrouterModelsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListModelsApiOpenrouterModelsPostError = ListModelsApiOpenrouterModelsPostErrors[keyof ListModelsApiOpenrouterModelsPostErrors];

export type ListModelsApiOpenrouterModelsPostResponses = {
    /**
     * Response List Models Api Openrouter Models Post
     *
     * Successful Response
     */
    200: Array<ModelInfo>;
};

export type ListModelsApiOpenrouterModelsPostResponse = ListModelsApiOpenrouterModelsPostResponses[keyof ListModelsApiOpenrouterModelsPostResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Response Health Check Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthCheckHealthGetResponse = HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Response Root  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type RootGetResponse = RootGetResponses[keyof RootGetResponses];

export type GetMetricsMetricsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/metrics';
};

export type GetMetricsMetricsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
